### ISSUE TITLE
libjingle_peerconnection_so.so is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by sandyye1981** [DyncBoyuan/AppRTC-AndroidStudio#1]
Hi, Eric

我尝试了这个demo，发现我的nexus 5 32bit ARM的手机没问题。

但如果换成64bit ARM的手机会发现报这个问题“libjingle_peerconnection_so.so is 32-bit instead of 64-bit“。

我想问下，是不是arm64-v8a里面的libjingle_peerconnection_so.so不是64 bit的

**Comment by DyncEric** [comment]
ok，我明天更新一下 
------------------ Original ------------------

**Comment by DyncEric** [comment]
这边开发环境要重新配置一下，等编译好了通知你哈

**Comment by sandyye1981** [comment]
是呀，原来自己在mac上download了自己编译，发现只有ios版可以，android版不行，查了一下，原来只能在liunx上，比如ubuntu上下载编译才行，但ubuntu上又遇到vpn难搞的问题，那现在只能找两台32bit的先测试下。

**Comment by DyncEric** [comment]
已经更新了64位的库
